backend:
  name: github
  repo: Kamony/video-blog
media_folder: static/assets
public_folder: assets
collections:
  - name: tag
    label: Tag
    create: true
    identifier_field: tag
    folder: model/tags
    fields:
      - name: tag
        label: Tag
        widget: string
  - name: section
    label: Section
    create: true
    identifier_field: section
    folder: model/sections
    fields:
      - name: section
        label: Section
        widget: string
      - name: slug
        label: Slug
        widget: string
      - name: color
        label: Color
        widget: string
        required: false
  - name: blog
    label: Blog
    folder: model/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: lead, label: Lead }
      - { name: featured, label: Featured, widget: boolean, default: false }
      - name: section,
        label: Section
        widget: relation
        collection: section
        searchFields: ['section']
        valueField: section
        multiple: false
      - name: tags,
        label: Tags
        widget: relation
        collection: tag
        searchFields: ['tag']
        valueField: tag
        multiple: true
      - { name: video, label: Video }
      - { name: body, label: Body, widget: markdown }
